### PR TITLE
Fixes for TestHarness

### LINKED ISSUE #7: MissileController is lost on Player.CopyAndFlip
Seems to be missing.

The following fixes it:

```
if (player.MissileController != null)
{
  copy.MissileController = MissileController.CopyAndFlip(player.MissileController, flipper, flippedEntities);
}
```

Let me know if you want a PR.

### PR DESCRIPTION
**Pull request by leppie**
Note: I kept your indent size, but VS auto formatting added some extra spacing.

Fixes: https://github.com/EntelectChallenge/2015-SpaceInvaders-TestHarness/issues/7 and the other isse noted on http://forum.entelect.co.za/thread/test-harness-player-2-ship/

### CODE REVIEW

**Comment by mattpwest** [comment]
Thanks for the fixes - looks good.

**Comment by leppie** [comment]
My only concern is that alien wave size cannot be larger than 6 and this will be hit before 160 rounds (0:3, 40:4, 80:5, 120:6). 

The only solution I think is alien wave size needs to be limited based on the map's width 
(iow `(width - (2 - 1)) / 3`).

Alternatively, it could start at say 2, but even then when alien factory is present, it will overflow.

Maybe increase wavesizeincreaselevel to say 50 or more.

I havent seen any of above happen though in about 1000 matches.

**Comment by mattpwest** [comment]
The Alien wave size should only increase once on round 40 - it's not every 40 rounds. See: https://github.com/EntelectChallenge/2015-SpaceInvaders-TestHarness/blob/master/SpaceInvaders/Core/Match.cs#L521

So after round 40 with an AlienFactory reaches the maximum wave size of 5.

**Comment by leppie** [comment]
Ah, cool, I misunderstood :) No wonder I did not see the problem manifest.

**Pull request merged**
